version: '3'

networks:
    altsso_net:

services:
    nginx:
        image: nginx:1.17-alpine
        container_name: altsso-nginx
        restart: unless-stopped
        depends_on:
            - app
            - mysql
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www/html
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - altsso_net

    mysql:
        image: mysql:8.0.21
        container_name: altsso_mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3307:3306"
        volumes: 
            - ./mysql/db:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: sso
            MYSQL_USER: satuakun
            MYSQL_PASSWORD: "SatuakunDB%6&"
            MYSQL_ROOT_PASSWORD: adminmysql
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - altsso_net

    app:
        build: 
            args:
                user: febrianrz
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: altsso_php
        volumes: 
            - ./src:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports: 
            - "9000:9000"
        networks: 
            - altsso_net
    
    phpmyadmin:
        container_name: altsso_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "33070:80"
        links: 
            - mysql:db
        environment: 
            MYSQL_DATABASE: sso
            MYSQL_USER: satuakun
            MYSQL_PASSWORD: "SatuakunDB%6&"
            MYSQL_ROOT_PASSWORD: adminmysql
            UPLOAD_LIMIT: 3000000000
        networks: 
            - altsso_net

    